# Generated by Django 4.2.4 on 2023-09-19 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nitrogen', models.FloatField()),
                ('Fosfor', models.FloatField()),
                ('Kalium', models.FloatField()),
                ('image', models.ImageField(upload_to='images/')),
                ('tanaman', models.CharField(max_length=100)),
                ('perbaikan', models.BooleanField(default=False)),
            ],
        ),
    ]
